# Header
menu:
  首页: /
  归档: /archives
  订阅: /atom.xml
  关于: /about

# Content
excerpt_link: 阅读更多
content_max_width: 800px

# Sidebar
author:
  name: Runoneall
  work: 我的开发记录、随笔、以及其他...
  location: Yantai, China
  avatar_url: /images/avatar.webp

# Links:
links:

# github comment
git_commit:
  enable: false

# 百度统计
baidu:
  id:

# Miscellaneous
rss: /atom.xml
favicon: /images/favicon.ico
